ALTER TABLE personas DROP PRIMARY KEY, ADD PRIMARY KEY(PersonaID);
ALTER TABLE cursos DROP PRIMARY KEY, ADD PRIMARY KEY(CursoID);
ALTER TABLE matriculados_interesados DROP PRIMARY KEY, ADD PRIMARY KEY(PersonaID, CursoID);