CREATE TABLESPACE `ABDDBA_TBLS_cursos` ADD DATAFILE 'ABDDBA_DF_cursos.ibd' ENGINE=INNODB;
CREATE TABLESPACE `ABDDBA_TBLS_personas` ADD DATAFILE 'ABDDBA_DF_personas.ibd' ENGINE=INNODB;
CREATE TABLESPACE `ABDDBA_TBLS_matriculados` ADD DATAFILE 'ABDDBA_DF_matriculados.ibd' ENGINE=INNODB;